<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" ng-app="magento"
      lang="<?php echo $this->getLang() ?>">
<head>
    <?php echo $this->getChildHtml('head') ?>
    <!--    START ANGULAR SCRIPTS -->
    <?php echo $this->getChildHtml('angular.scripts') ?>
    <!--    END ANGULAR SCRIPTS -->
</head>
<body id="html-body"<?php echo $this->getBodyClass() ? ' class="' . $this->getBodyClass() . '"' : ''; ?>>
<div class="off-canvas-wrap" data-offcanvas>
    <div class="inner-wrap">
        <aside class="right-off-canvas-menu">
            <?php echo $this->getChildHtml("offcanvas.right") ?>
        </aside>


        <?php echo $this->getChildHtml('notification_window'); ?>
        <div class="wrapper">
            <?php echo $this->getChildHtml('global_notices') ?>
            <div class="header">
                <?php echo $this->getChildHtml('header') ?>
                <div class="clear"></div>
                <?php echo $this->getChildHtml('menu') ?>
            </div>
            <?php echo $this->getChildHtml('notifications'); ?>
            <div class="middle" id="anchor-content">
                <div id="page:main-container">
                    <?php if ($this->getChildHtml('left')): ?>

                        <div class="<?php echo $this->getContainerCssClass() ?>">
                            <div class="side-col" id="page:left">
                                <?php echo $this->getChildHtml('left') ?>
                            </div>
                            <div class="main-col" id="content">
                                <div class="main-col-inner">
                                    <div id="messages"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
                                    <?php echo $this->getChildHtml('content') ?>
                                </div>
                            </div>
                        </div>

                    <?php else: ?>
                        <div id="messages"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
                        <?php echo $this->getChildHtml('content') ?>
                    <?php endif; ?>
                </div>
            </div>
            <div class="footer">
                <?php echo $this->getChildHtml('footer') ?>
            </div>
        </div>
        <?php echo $this->getChildHtml('js') ?>
        <?php echo $this->getChildHtml('profiler') ?>
        <div id="loading-mask" style="display:none">
            <p class="loader" id="loading_mask_loader"><img
                    src="<?php echo $this->getSkinUrl('images/ajax-loader-tr.gif') ?>"
                    alt="<?php echo Mage::helper('adminhtml')->__(
                        'Loading...'
                    ) ?>"/><br/><?php echo Mage::helper('adminhtml')->__(
                    'Please wait...'
                ) ?></p>
        </div>

        <?php echo $this->getChildHtml('before_body_end') ?>
        <a class="exit-off-canvas"></a>
    </div>
</div>
<script> jQuery(document).foundation({
        equalizer: {
            equalize_on_stack: true
        },
        abide: {
            live_validate: true
        },
        joyride: {
            expose: true,
            modal: true
        }
    }); </script>
</body>
</html>

